### PR TITLE
1.21.11

### LINKED ISSUE #507: [Bug] Armor stands render entirely black (Fabric, 1.21.10)
### Bug Description

All armor stands are rendered as being pitch-black. 

### How to Reproduce?

1. Launch the game running Fabric 1.21.10 and this mod
2. Place an armor stand
3. Armor stand renders as entirely pitch-black, regardless of the presence of armor (or lack thereof)

### Expected Behavior

Armor stands render as they do in vanilla

### Version

1.21.10-1.0

### Fabric/Quilt Loader Version

0.17.3

### Logs or additional context

https://mclo.gs/d9rPQDY

### Has not been reported.

- [x] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [x] I made sure I am using the most up to date fabric/quilt loader and mod version.

### LINKED ISSUE #514: 1.21.11
Obligatory 1.21.11 issue

### PR DESCRIPTION
**Pull request by Rektroth**
Port to 1.21.11. Closes #514.

Removes the fixes for MC-22882 and MC-199467, as they were marked as resolved as of 1.21.11.

Includes the fix for armor stands rendering dark (from #509, closes #507) and the corrected description for MC-121903 (#511).

**Potential issues:**
This PR, like, actually sucks, because:
- To get builds working, I had to update Loom, Gradle, and Modstitch. I have no idea if I did this the "proper" way.
- The No-YACL screen may be broken - YACL appears to be pre-included, at least in the development environment, and I'm not sure how to disable this.
- I especially had trouble with the fix for MC-237493. I don't like the solution I came up with, and I haven't tested it thoroughly.

### CODE REVIEW

File: src/client/java/dev/isxander/debugify/client/mixins/basic/mc237493/TelemetryInfoScreenMixin.java [hunk 1]
```diff
@@ -25,8 +28,8 @@ public class TelemetryInfoScreenMixin {
...
      * @reason
      */
-    @Overwrite
-    private AbstractWidget createTelemetryCheckbox() {
-        return ((DebugifyTelemetryAccessor) options).getTelemetryOption().createButton(options, 0, 0, 308, state -> telemetryEventWidget.onOptInChanged(state == DebugifyTelemetry.ALL));
+    @WrapOperation(method = "init", at = @At(ordinal = 5, value = "INVOKE", target = "Lnet/minecraft/client/gui/layouts/LinearLayout;addChild(Lnet/minecraft/client/gui/layouts/LayoutElement;)Lnet/minecraft/client/gui/layouts/LayoutElement;"))
+    private LayoutElement createTelemetryCheckbox(LinearLayout layout, LayoutElement child, Operation<LayoutElement> original) {
+        return original.call(layout, ((DebugifyTelemetryAccessor) options).getTelemetryOption().createButton(options, 0, 0, 308, state -> telemetryEventWidget.onOptInChanged(state == DebugifyTelemetry.ALL)));
     }
 }
```
Comment (MicrocontrollersDev) [inline src/client/java/dev/isxander/debugify/client/mixins/basic/mc237493/TelemetryInfoScreenMixin.java]: Github isn't letting me suggest changes here so here's my entire class.

```
package dev.isxander.debugify.client.mixins.basic.mc237493;

import com.llamalad7.mixinextras.expression.Definition;
import com.llamalad7.mixinextras.expression.Expression;
import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
import com.llamalad7.mixinextras.injector.wrapoperation.WrapOperation;
import dev.isxander.debugify.client.helpers.mc237493.DebugifyTelemetry;
import dev.isxander.debugify.client.helpers.mc237493.DebugifyTelemetryAccessor;
import dev.isxander.debugify.fixes.BugFix;
import dev.isxander.debugify.fixes.FixCategory;
import net.minecraft.client.Options;
import net.minecraft.client.gui.components.AbstractWidget;
import net.minecraft.client.gui.layouts.LayoutElement;
import net.minecraft.client.gui.layouts.LinearLayout;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.gui.screens.telemetry.TelemetryEventWidget;
import net.minecraft.client.gui.screens.telemetry.TelemetryInfoScreen;
import net.minecraft.network.chat.Component;
import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@BugFix(id = "MC-237493", category = FixCategory.BASIC, env = BugFix.Env.CLIENT, modConflicts = "no-telemetry", description = "Telemetry cannot be disabled")
@Mixin(TelemetryInfoScreen.class)
public abstract class TelemetryInfoScreenMixin extends Screen {
    protected TelemetryInfoScreenMixin(Component title) {
        super(title);
    }

    @Shadow @Final private Options options;

    @Shadow private TelemetryEventWidget telemetryEventWidget;

    @Unique private AbstractWidget cycleButton;

    @Definition(id = "addChild", method = "Lnet/minecraft/client/gui/layouts/LinearLayout;addChild(Lnet/minecraft/client/gui/layouts/LayoutElement;)Lnet/minecraft/client/gui/layouts/LayoutElement;")
    @Definition(id = "builder", method = "Lnet/minecraft/client/gui/components/Checkbox;builder(Lnet/minecraft/network/chat/Component;Lnet/minecraft/client/gui/Font;)Lnet/minecraft/client/gui/components/Checkbox$Builder;")
    @Definition(id = "CHECKBOX_OPT_IN", field = "Lnet/minecraft/client/gui/screens/telemetry/TelemetryInfoScreen;CHECKBOX_OPT_IN:Lnet/minecraft/network/chat/Component;")
    @Expression("?.addChild(builder(CHECKBOX_OPT_IN, ?).?(?).?(?.?.?()).?(?).?())")
    @WrapOperation(method = "init", at = @At("MIXINEXTRAS:EXPRESSION"))
    private LayoutElement createTelemetryCheckbox(LinearLayout instance, LayoutElement child, Operation<LayoutElement> original) {
        this.cycleButton = instance.addChild(((DebugifyTelemetryAccessor) options).getTelemetryOption().createButton(options, 0, 0, 308, state -> telemetryEventWidget.onOptInChanged(state == DebugifyTelemetry.ALL)));
        return null;
    }

    @Inject(method = "repositionElements", at = @At("TAIL"))
    private void repositionCycleButton(CallbackInfo ci) {
        if (this.cycleButton != null) {
            this.cycleButton.setWidth(308);
        }
    }
}
```

File: src/client/java/dev/isxander/debugify/client/mixins/basic/mc115092/SquidRendererMixin.java
[the remark this answers is not in the document]
Comment (Rektroth) [reply src/client/java/dev/isxander/debugify/client/mixins/basic/mc115092/SquidRendererMixin.java]: Yeah, figured it out. Weird I never got an error from this.

File: src/client/java/dev/isxander/debugify/client/mixins/basic/mc237493/TelemetryInfoScreenMixin.java (hunk 1 above)
Comment (Rektroth) [reply src/client/java/dev/isxander/debugify/client/mixins/basic/mc237493/TelemetryInfoScreenMixin.java]: Obviously much better than mine.

File: src/client/java/dev/isxander/debugify/client/mixins/basic/mc115092/SquidRendererMixin.java
[the remark this answers is not in the document]
Comment (MicrocontrollersDev) [reply src/client/java/dev/isxander/debugify/client/mixins/basic/mc115092/SquidRendererMixin.java]: Yeah it's one I missed as well in my initial port. It only gives a missing target error warning when launching the game, and god knows how it launches in the first place

File: build.gradle.kts [hunk 2]
```diff
@@ -212,14 +213,14 @@ val generatePatchedTable by tasks.registering {
...
-        val timestamp = `java.time`.LocalDateTime.now().format(`java.time.format`.DateTimeFormatter.ISO_DATE_TIME)
+        //val timestamp = `java.time`.LocalDateTime.now().format(`java.time.format`.DateTimeFormatter.ISO_DATE_TIME)
 
         val markdownTable = """
             - <!--
             - !!!! DO NOT UPDATE THIS FILE MANUALLY !!!!
             - Generated by `./gradlew generatePatchedTable`
             - Sourced from `${inputFile.name}`
-            - Generated $timestamp
+            - Generated now
```
Comment (isXander) [inline build.gradle.kts]: ???

Comment (Rektroth) [reply build.gradle.kts]: Ah, yes. I was having trouble building:

```
* What went wrong:
Script compilation errors:

  Line 216:         val timestamp = `java.time`.LocalDateTime.now().format(`java.time.format`.DateTimeFormatter.ISO_DATE_TIME)
                                                ^ Unresolved reference 'LocalDateTime'.

  Line 216:         val timestamp = `java.time`.LocalDateTime.now().format(`java.time.format`.DateTimeFormatter.ISO_DATE_TIME)
                                                                                              ^ Unresolved reference 'DateTimeFormatter'.
```

This was my fix just so that I could build.

I've removed it.
